# Generated by Django 4.2.11 on 2025-03-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_ran_number',
            field=models.IntegerField(default=1),
        ),
    ]
