# Generated by Django 4.2.11 on 2025-03-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentid',
            options={'ordering': ['studentId']},
        ),
    ]
