# Generated by Django 5.1.7 on 2025-03-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subject_subjectmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subjectMarks',
            new_name='Subject_marks',
        ),
    ]
