# Generated by Django 5.1.7 on 2025-03-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_subjectmarks_subject_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_marks',
            old_name='market',
            new_name='marks',
        ),
    ]
