# Generated by Django 5.1.7 on 2025-03-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_market_subject_marks_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject_marks',
        ),
    ]
