# Generated by Django 5.1.7 on 2025-03-13 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_subject_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentmarks', to='home.student'),
        ),
    ]
