# Generated by Django 5.1.7 on 2025-03-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_reportcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='report_card_generated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'report_card_generated_date')},
        ),
    ]
