# Generated by Django 5.1.7 on 2025-03-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_reportcard_report_card_generated_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportCard',
        ),
    ]
